config/routes.rb
Rails.application.routes.draw do
  get 'ad/home'

  resources :profiles
  resources :advertisements

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  belongs_to :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/controllers/ad_controller.rb
class AdController < ApplicationController
  def home
@ads=Advertisement.select("id","profile_id","name","cost","acost","bcost","balance","active","date").all

  end
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]

  # GET /advertisements
  # GET /advertisements.json
  def index
    @advertisements = Advertisement.all
  end

  # GET /advertisements/1
  # GET /advertisements/1.json
  def show
  end

  # GET /advertisements/new
  def new
    @advertisement = Advertisement.new
  end

  # GET /advertisements/1/edit
  def edit
  end

  # POST /advertisements
  # POST /advertisements.json
  def create
    @advertisement = Advertisement.new(advertisement_params)
    if(@advertisement[:acost].to_i==@advertisement[:cost].to_i)
      @advertisement[:bcost]=0
      @advertisement[:balance]=false
      @advertisement[:active]=true
      puts "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
    else 

      puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
      @advertisement[:bcost]=(@advertisement[:cost].to_i-@advertisement[:acost].to_i)
      @advertisement[:balance]=true
      @advertisement[:active]=true
    
     end
    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully created.' }
        format.json { render :show, status: :created, location: @advertisement }
      else
        format.html { render :new }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisements/1
  # PATCH/PUT /advertisements/1.json
  def update
    respond_to do |format|
      if @advertisement.update(advertisement_params)
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertisement }
      else
        format.html { render :edit }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisements/1
  # DELETE /advertisements/1.json
  def destroy
    @advertisement.destroy
    respond_to do |format|
      format.html { redirect_to advertisements_url, notice: 'Advertisement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisement_params
      params.require(:advertisement).permit(:profile_id, :name, :atype, :cost, :acost, :bcost, :active, :balance, :date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :cname, :addr, :mob)
    end
end

app/helpers/ad_helper.rb
module AdHelper
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/ad/home.html.erb
<!DOCTYPE html>
<html ng-app="ad">
<head>


	<title></title>


<script type="text/javascript">
	var app=angular.module('ad',[])
app.controller('m', function($scope) {

	$scope.s=<%=@ads.to_json.html_safe%>;	
	

});

</script>

</head>
<body ng-controller="m"><input  type="search"ng-model="ss.$" ></input>
 <label id="search">Search</label><input  type="search"ng-model="ss.name" ></input>
<label>Date</label> <input type="checkbox" ng-false-value=""ng-true-value="<%=Time.now.strftime("%Y-%m-%d ")%>" ng-model="ss.date">
 <label >Active</label><input  type="checkbox"  ng-model="ss.active" ></input>
<input  type="checkbox"  ng-model="ss.balance" ></input>

<ol >
	<li ng-repeat="i in s |filter:ss:strict">
		{{i.name}}-{{i.cost}}-{{i.enddate}}
	</li>
</ol>
{{s}}
</body>
</html>

app/views/advertisements/_form.html.erb
<%= form_for(@advertisement) do |f| %>
  <% if @advertisement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertisement.errors.count, "error") %> prohibited this advertisement from being saved:</h2>

      <ul>
      <% @advertisement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_id %><br>
    <%= f.collection_select(:profile_id,Profile.all,:id,:name)%>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :atype %><br>
    <%= f.text_field :atype %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :acost %><br>
    <%= f.number_field :acost %>
  </div>
  <div class="field">
    <%= f.label :bcost %><br>
    <%= f.number_field :bcost %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.check_box :balance %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advertisements/edit.html.erb
<h1>Editing Advertisement</h1>

<%= render 'form' %>

<%= link_to 'Show', @advertisement %> |
<%= link_to 'Back', advertisements_path %>

app/views/advertisements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Advertisements</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Name</th>
      <th>Atype</th>
      <th>Cost</th>
      <th>Acost</th>
      <th>Bcost</th>
      <th>Active</th>
      <th>Balance</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advertisements.each do |advertisement| %>
      <tr>
        <td><%= advertisement.profile %></td>
        <td><%= advertisement.name %></td>
        <td><%= advertisement.atype %></td>
        <td><%= advertisement.cost %></td>
        <td><%= advertisement.acost %></td>
        <td><%= advertisement.bcost %></td>
        <td><%= advertisement.active %></td>
        <td><%= advertisement.balance %></td>
        <td><%= advertisement.date %></td>
        <td><%= link_to 'Show', advertisement %></td>
        <td><%= link_to 'Edit', edit_advertisement_path(advertisement) %></td>
        <td><%= link_to 'Destroy', advertisement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advertisement', new_advertisement_path %>

app/views/advertisements/new.html.erb
<h1>New Advertisement</h1>

<%= render 'form' %>

<%= link_to 'Back', advertisements_path %>

app/views/advertisements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @advertisement.profile %>
</p>

<p>
  <strong>Name:</strong>
  <%= @advertisement.name %>
</p>

<p>
  <strong>Atype:</strong>
  <%= @advertisement.atype %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @advertisement.cost %>
</p>

<p>
  <strong>Acost:</strong>
  <%= @advertisement.acost %>
</p>

<p>
  <strong>Bcost:</strong>
  <%= @advertisement.bcost %>
</p>

<p>
  <strong>Active:</strong>
  <%= @advertisement.active %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @advertisement.balance %>
</p>

<p>
  <strong>Date:</strong>
  <%= @advertisement.date %>
</p>

<%= link_to 'Edit', edit_advertisement_path(@advertisement) %> |
<%= link_to 'Back', advertisements_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ads</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cname %><br>
    <%= f.text_field :cname %>
  </div>
  <div class="field">
    <%= f.label :addr %><br>
    <%= f.text_field :addr %>
  </div>
  <div class="field">
    <%= f.label :mob %><br>
    <%= f.text_field :mob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cname</th>
      <th>Addr</th>
      <th>Mob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.cname %></td>
        <td><%= profile.addr %></td>
        <td><%= profile.mob %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Cname:</strong>
  <%= @profile.cname %>
</p>

<p>
  <strong>Addr:</strong>
  <%= @profile.addr %>
</p>

<p>
  <strong>Mob:</strong>
  <%= @profile.mob %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>